CREATE TABLE IF NOT EXISTS tcm_diagnosis (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    patient_id BIGINT NOT NULL,
    doctor_id BIGINT,
    doctor_name VARCHAR(64),
    diagnosis_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    main_complaint TEXT,
    tongue_description TEXT,
    tongue_image_url VARCHAR(255),
    pulse_description TEXT,
    tcm_summary TEXT,
    physical_exam TEXT,
    lifestyle TEXT,
    status VARCHAR(16) NOT NULL DEFAULT 'COMPLETED',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ext1 VARCHAR(255),
    ext2 VARCHAR(255),
    ext3 VARCHAR(255),
    ext4 VARCHAR(255),
    ext5 VARCHAR(255),
    INDEX idx_tcm_diagnosis_patient (patient_id),
    INDEX idx_tcm_diagnosis_date (diagnosis_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;